Repository iodide-project/iodide, pull requests merged in 2018-06, with the labels that each got.

#631 Add support for importing ipynb files
  src/tools/handle-url-query.js
  src/tools/ipynb-import.js
Labels: demo, enhancement, jupyter parity

#635 Array / String fixes
  src/components/reps/array-handler.jsx
  src/components/reps/null-handler.jsx
  src/components/reps/undefined-handler.jsx
  src/components/reps/value-renderer.jsx
  src/style/cell-styles.css
  src/style/page.css
Labels: UI, bug, output formatting

#617 creates a snackbar that appears when app messages are recorded
  src/actions/__tests__/actions.test.js
  src/actions/actions.js
  src/actions/task-definitions.js
  src/components/app-messages/app-messages.jsx
  src/components/page.jsx
  src/components/panes/app-info-pane.jsx
  src/reducers/create-validated-reducer.js
  src/reducers/notebook-reducer.js
  src/state-prototypes.js
  src/style/side-panes.css
Labels: UI

#647 fixed state obliteration bug that somehow surfaced in last pr
  src/reducers/notebook-reducer.js
Labels: bug

#618 added evalQueue.await to the iodide api
  src/iodide-api/__test__/evalQueue.test.js
  src/iodide-api/evalQueue.js
  src/state-prototypes.js
Labels: iodide api

#675 very small css tweaks while we work on functionality
  src/components/eval-frame.jsx
  src/eval-frame/style/page.css
  src/style/page.css
Labels: iodide-next

#676 removed localStorage from eval-frame
  src/eval-frame/actions/task-definitions.js
  src/eval-frame/components/cells/cell-menu-container.js
  src/eval-frame/components/page.jsx
  src/eval-frame/components/panes/side-pane.jsx
  src/eval-frame/reducers/__tests__/notebook-reducer.test.js
  src/eval-frame/reducers/notebook-reducer.js
Labels: iodide-next

#680 remove iodide-api from the editor scope
  src/index.jsx
  src/iodide-api/__test__/environment.test.js
  src/iodide-api/__test__/evalQueue.test.js
  src/iodide-api/api.js
  src/iodide-api/environment.js
  src/iodide-api/evalQueue.js
  src/iodide-api/output.js
Labels: iodide-next

#681 removed all CodeMirror references in eval-frame
  src/eval-frame/components/cells/cell-editor.jsx
  src/eval-frame/components/panes/history-item.jsx
Labels: iodide-next

#682 nb-tests -> iframe-2
  src/tools/__tests__/nb.test.js
  src/tools/nb.js
Labels: iodide-next

#683 added the nb tests / tweaks to eval frame
  src/eval-frame/tools/__tests__/nb.test.js
  src/eval-frame/tools/nb.js
Labels: iodide-next

#684 refactor eval-frame pieces, remove redundancies
  src/eval-frame/actions/__tests__/user-task.test.js
  src/eval-frame/actions/external-link-task.js
  src/eval-frame/actions/task-definitions.js
  src/eval-frame/actions/user-task.js
  src/eval-frame/codemirror-keymap-sublime.js
  src/eval-frame/components/cells/__tests__/cell-output.test.js
  src/eval-frame/components/cells/__tests__/external-resource-cell.test.js
  src/eval-frame/components/cells/cell-output.jsx
  src/eval-frame/components/cells/external-resource-cell.jsx
  src/eval-frame/components/eval-container.jsx
  src/eval-frame/components/panes/declared-variable.jsx
  src/eval-frame/components/panes/side-pane.jsx
  src/eval-frame/components/reps/__tests__/array-handler.test.js
  src/eval-frame/components/reps/__tests__/dataframe-handler.test.js
  src/eval-frame/components/reps/__tests__/date-handler.test.js
  src/eval-frame/components/reps/__tests__/matrix-handler.test.js
  src/eval-frame/components/reps/__tests__/null-handler.test.js
  src/eval-frame/components/reps/__tests__/promise-handler.test.jsx
  src/eval-frame/components/reps/__tests__/scalar-handler.test.js
  src/eval-frame/components/reps/__tests__/undefined-handler.test.js
  src/eval-frame/components/reps/array-handler.jsx
  src/eval-frame/components/reps/dataframe-handler.jsx
  src/eval-frame/components/reps/date-handler.jsx
  src/eval-frame/components/reps/default-handler.jsx
  src/eval-frame/components/reps/dom-element-handler.jsx
  src/eval-frame/components/reps/matrix-handler.jsx
  src/eval-frame/components/reps/null-handler.jsx
  src/eval-frame/components/reps/output-handler-external-resource.jsx
  src/eval-frame/components/reps/pretty-matrix.jsx
  src/eval-frame/components/reps/promise-handler.jsx
  src/eval-frame/components/reps/scalar-handler.jsx
  src/eval-frame/components/reps/undefined-handler.jsx
  src/eval-frame/components/reps/value-renderer.jsx
  src/eval-frame/index.jsx
  src/eval-frame/iodide-api/api.js
  src/eval-frame/iodide-examples.js
  src/eval-frame/style/menu-styles.css
  src/eval-frame/tools/__tests__/jsmd-tools_parse.test.js
  src/eval-frame/tools/__tests__/jsmd-tools_serialize.test.js
  src/eval-frame/tools/handle-url-query.js
  src/eval-frame/tools/jsmd-tools.js
  src/index.jsx
  src/style/default-presentation.css
Labels: iodide-next

#686 fixed messagepassing error from not checking for string
  src/port-to-eval-frame.js
Labels: iodide-next

#687 eval-frame cells -> outputs, other reorganization
  src/eval-frame/actions/eval-frame-tasks.js
  src/eval-frame/components/cells/__tests__/code-cell-test.test.js
  src/eval-frame/components/cells/__tests__/css-cell.test.js
  src/eval-frame/components/cells/__tests__/external-resource-cell.test.js
  src/eval-frame/components/cells/__tests__/markdown-cell.test.js
  src/eval-frame/components/cells/__tests__/raw-cell.test.js
  src/eval-frame/components/cells/code-cell.jsx
  src/eval-frame/components/cells/plugin-definition-cell.js
  src/eval-frame/components/cells/raw-cell.jsx
  src/eval-frame/components/eval-container.jsx
  src/eval-frame/components/outputs/__tests__/code-output.test.js
  src/eval-frame/components/outputs/__tests__/css-output.test.js
  src/eval-frame/components/outputs/__tests__/external-resource-output.test.js
  src/eval-frame/components/outputs/__tests__/markdown-output.test.js
  src/eval-frame/components/outputs/__tests__/output-container.test.js
  src/eval-frame/components/outputs/__tests__/output-renderer.test.js
  src/eval-frame/components/outputs/__tests__/output-row.test.js
  src/eval-frame/components/outputs/__tests__/raw-output.test.js
  src/eval-frame/components/outputs/code-output.jsx
  src/eval-frame/components/outputs/css-output.jsx
  src/eval-frame/components/outputs/external-resource-output.jsx
  src/eval-frame/components/outputs/markdown-output.jsx
  src/eval-frame/components/outputs/output-container.jsx
  src/eval-frame/components/outputs/output-renderer.jsx
  src/eval-frame/components/outputs/output-row.jsx
  src/eval-frame/components/outputs/plugin-definition-output.jsx
  src/eval-frame/components/outputs/raw-output.jsx
  src/eval-frame/components/panes/app-info-pane.jsx
  src/eval-frame/components/panes/declared-variables-pane.jsx
  src/eval-frame/components/panes/history-pane.jsx
  src/eval-frame/components/panes/side-pane.jsx
  src/eval-frame/index.jsx
  src/eval-frame/initialize-notebook.js
  src/eval-frame/keybindings.js
  src/eval-frame/store.js
  src/eval-frame/style/cell-styles.css
  src/eval-frame/style/eval-container.css
  src/eval-frame/style/page.css
Labels: iodide-next
