Repository iodide-project/iodide, pull requests merged in 2019-02, with the labels that each got.

#1524 JSS-based components (material-ui) now come before emotion styles (thus fixing the cascade issue)
  CHANGELOG.md
  package.json
  src/eval-frame/index.jsx
  src/index.jsx
  src/shared/css-cascade-provider.jsx
Labels: bug, client UX

#1511 separate out inputs & outputs, refactor history items to have consistent design
  CHANGELOG.md
  src/actions/__tests__/eval-frame-action-validator.test.js
  src/actions/actions.js
  src/actions/eval-frame-action-validator.js
  src/components/reps/default-handler.jsx
  src/components/reps/error-handler.jsx
  src/components/reps/preformatted-text-items-handler.jsx
  src/eval-frame/actions/actions.js
  src/eval-frame/actions/fetch-cell-eval-actions.js
  src/eval-frame/actions/language-actions.js
  src/eval-frame/components/panes/__tests__/history-item.test.js
  src/eval-frame/components/panes/console-pane.jsx
  src/eval-frame/components/panes/console/app-message.jsx
  src/eval-frame/components/panes/console/base-icon.jsx
  src/eval-frame/components/panes/console/console-container.jsx
  src/eval-frame/components/panes/console/console-language-menu.jsx
  src/eval-frame/components/panes/console/console-message.jsx
  src/eval-frame/components/panes/console/history-input-item.jsx
  src/eval-frame/components/panes/console/log-levels.jsx
  src/eval-frame/components/panes/history-item.jsx
  src/eval-frame/components/panes/pane-content-button.jsx
  src/eval-frame/style/eval-container.css
  src/reducers/eval-frame-reducer.js
  src/state-schemas/state-schema.js
Labels: client UX

#1544 Add a link to the user's github profile on the user page
  CHANGELOG.md
  server/tests/test_server_pages.py
  server/views.py
  src/server/pages/user-page.jsx
Labels: iodide-server
